site_name: BlueROV
# docs_dir: './'
# theme: united
# use_directory_urls: false
repo_url: https://github.com/bluerobotics/BlueROV
markdown_extensions: ['tables']
pages:
- ['index.md', 'Home']
- ['Vehicle.md', 'Vehicle']
- ['Setup.md', 'Setup']
- ['Usage.md', 'Usage']
- ['Sprint Notes.md', 'Sprint Notes']
- ['Wet Test Checklist.md', 'Wet Test Checklist']
- ['Change History.md', 'Change History']
