site_name: BlueROV
theme: cerulean
repo_url: https://github.com/bluerobotics/BlueROV
markdown_extensions: ['tables']
pages:
- ['index.md', 'Home']
- ['Setup.md', 'Setup']
- ['Usage.md', 'Usage']
- ['Wet Test Checklist.md', 'Wet Test Checklist']
- ['Sprint Notes.md', 'Sprint Notes']
- ['Test Results.md', 'Test Results']
- ['Change History.md', 'Change History']
