site_name: BlueROV
theme: cerulean
repo_url: https://github.com/bluerobotics/BlueROV
markdown_extensions: ['tables']
pages:
- ['index.md', 'Home']
- ['Setup.md', 'Setup']
- ['Usage.md', 'Usage']
- ['Checklist.md', 'Checklist']
- ['Test Results.md', 'Test Results']
- ['Change History.md', 'Change History']
- ['Todo.md', 'Todo']
